databases:
  - name: mysite3
    databaseName: mysite3
    user: mysite3
    plan: standard # 有料プランに変更

services:
  - type: web
    name: mysite3
    runtime: ruby
    plan: standard # 有料プランに変更
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "bundle exec rails db:migrate" # 有料プランでのみ利用可能
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite3
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default